kind: postgresql
apiVersion: acid.zalan.do/v1

metadata:
  name: postgres
  namespace: addons
  labels:
    team: acid

spec:
  teamId: acid
  postgresql:
    version: "13"
  numberOfInstances: 1
  volume:
    size: 5Gi
    storageClass: gp3
  users:
    n8n:
      - createdb
      - password: "n8n"

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
