airflow:
  multiNamespaceMode: False
  # Airflow Configurations
  config:
    celery:
      worker_concurrency: 16  # Adjust based on your needs

  # Airflow Executor Settings
  executor: "CeleryKubernetesExecutor"
  kubernetes:
    airflow_configmap: "{{ include 'airflow_config' . }}"
    pod_template_file: "{{ include 'airflow_pod_template_file' . }}/pod_template_file.yaml"
    worker_container_repository: "{{ .Values.images.airflow.repository | default .Values.defaultAirflowRepository }}"
    worker_container_tag: "{{ .Values.images.airflow.tag | default .Values.defaultAirflowTag }}"
  
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
  
  migrateDatabaseJob:
    jobAnnotations:
        "argocd.argoproj.io/hook": Sync

  # Scaling Configurations
  keda:
    enabled: False
    pollingInterval: 5
    cooldownPeriod: 30
    minReplicaCount: 0
    maxReplicaCount: 10

  # Autoscaling (HPA)
  hpa:
    enabled: False
    minReplicaCount: 0
    maxReplicaCount: 5
    metrics:
      - type: "Resource"
        resource:
          name: "cpu"
          target:
            type: "Utilization"
            averageUtilization: 80

  # DAGs Repository
  dags:
    gitSync:
      enabled: False
      repo: "https://github.com/apache/airflow.git"
      branch: "v2-2-stable"
      depth: 1

  # Logging Configuration
  logs:
    persistence:
      enabled: False
      size: "100Gi"

  # Security Settings
  serviceAccount:
    create: True
    automountServiceAccountToken: True

  # Miscellaneous
  terminationGracePeriodSeconds: 600
  logGroomerSidecar:
    enabled: True
    retentionDays: 15

  # Ingress Configuration for Airflow Web Service
  ingress:
    web:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "airflow.digitalview.com.br"
        kubernetes.io/ingress.class: "gce"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      path: "/"
      pathType: "ImplementationSpecific"
      hosts:
        - name: "airflow.digitalview.com.br"
          tls:
            enabled: true
            secretName: "airflow-tls"


