n8n:
  config:
    database:
      type: postgresdb
      postgresdb:
        host: "postgres-n8n-postgresql.addons.svc.cluster.local"  # Update this with your PostgreSQL host
        port: 5432  # Update this with your PostgreSQL port
        database: "n8n"  # Update this with your PostgreSQL database name
        user: "n8n"  # Update this with your PostgreSQL user
  secret:
    database:
      postgresdb:
        password: "n8n"  # Update this with your PostgreSQL password
