n8n:
  config:
    database:
      type: postgresdb
      postgresdb:
        host: postgres-n8n-postgresql.databases.svc.cluster.local # Update this with your PostgreSQL host
        port: 5432  # Update this with your PostgreSQL port
        database: "n8n"  # Update this with your PostgreSQL database name
        user: "n8n"  # Update this with your PostgreSQL user
  secret:
    database:
      postgresdb:
        password: "n8n"  # Update this with your PostgreSQL password
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 90
  scaling:
    enabled: true
    worker:
      count: 2
      concurrency: 2
    webhook:
      enabled: true
      count: 1
