n8n:
  defaults:
    config:
      database:
        type: postgresdb
        postgresdb:
          host: "postgres.addons.svc.cluster.local"  # Update this with your PostgreSQL host
          port: 5432  # Update this with your PostgreSQL port
          user: "n8n"  # Update this with your PostgreSQL user
          password: "n8n"  # Update this with your PostgreSQL password
          database: "n8n"  # Update this with your PostgreSQL database name

